version: '3.1'

services:

  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  account-service:
    build: ./backend/accounts-service/
    restart: always
    ports:
      - 3000:3000