version: '3.7'

services:

  postgres:
    image: postgres:14.4-alpine
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  account-service:
    build: ./backend/accounts-service/
    restart: always
    ports:
      - 3000:3000
      
volumes:
  postgresdata:
    driver: local