FROM node:16-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .
RUN npm run build

FROM node:12-alpine AS server
WORKDIR /app
COPY --from=builder ./app/ .

CMD ["npm", "start"]
